module Mossy.Type
  ( Void
  , Float
  , Int
  , UInt
  , Bool
  , Vec2
  , Vec3
  , Vec4
  , BVec2
  , BVec3
  , BVec4
  , IVec2
  , IVec3
  , IVec4
  , UVec2
  , UVec3
  , UVec4
  , Mat2
  , Mat3
  , Mat4
  , Mat2x2
  , Mat2x3
  , Mat2x4
  , Mat3x2
  , Mat3x3
  , Mat3x4
  , Mat4x2
  , Mat4x3
  , Mat4x4
  , Sampler1D
  , Sampler2D
  , Sampler3D
  , SamplerCube
  , Sampler1DShadow
  , Sampler2DShadow
  , SamplerCubeShadow
  , Sampler1DArray
  , Sampler2DArray
  , Sampler1DArrayShadow
  , Sampler2DArrayShadow
  , ISampler1D
  , ISampler2D
  , ISampler3D
  , ISamplerCube
  , ISampler1DArray
  , ISampler2DArray
  , USampler1D
  , USampler2D
  , USampler3D
  , USamplerCube
  , USampler1DArray
  , USampler2DArray
  , Sampler2DRect
  , Sampler2DRectShadow
  , ISampler2DRect
  , USampler2DRect
  , SamplerBuffer
  , ISamplerBuffer
  , USamplerBuffer
  , Sampler2DMS
  , ISampler2DMS
  , USampler2DMS
  , Sampler2DMSArray
  , ISampler2DMSArray
  , USampler2DMSArray
  ) where

import Language.GLSL.Syntax
